# Generated by Django 3.0.3 on 2020-03-05 09:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsearcher', '0002_auto_20200304_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_related_name': 'Company'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='date',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='jobsearcher.Scope'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Company', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('EG', 'Engineering and Manufacturing'), ('BS', 'Business'), ('HC', 'HealthCare'), ('LW', 'Law')], default='IT', max_length=30),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearcher.Scope')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('last_modified', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='jobsearcher.Scope')),
                ('themes', models.ManyToManyField(related_name='applicants', to='jobsearcher.Theme')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
