# Generated by Django 3.0.3 on 2020-03-06 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsearcher', '0003_auto_20200305_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
                ('last_modified', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joboffers', to='jobsearcher.Company')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joboffers_mod', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joboffers', to='jobsearcher.Theme')),
            ],
            options={
                'default_related_name': 'JobOffer',
            },
        ),
    ]
