# Generated by Django 3.0.3 on 2020-03-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0004_joboffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zipCode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
