# Generated by Django 3.0.3 on 2020-03-20 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsearcher', '0004_joboffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'default_related_name': 'Applicant'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='Applicant', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField()),
                ('created', models.DateField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsearcher.Applicant')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearcher.Company')),
                ('jobOffer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsearcher.JobOffer')),
            ],
        ),
    ]
