# Generated by Django 3.0.3 on 2020-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0005_company_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='zipCode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
