# Generated by Django 3.0.3 on 2020-03-12 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0008_auto_20200307_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joboffers', to='jobsearcher.Theme'),
        ),
    ]
