# Generated by Django 3.0.3 on 2020-03-12 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0009_auto_20200312_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='joboffers', to='jobsearcher.Company'),
        ),
    ]
