# Generated by Django 3.0.3 on 2020-03-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0010_auto_20200312_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='jobsearcher.Scope'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, related_name='applicants', to='jobsearcher.Theme'),
        ),
    ]
