# Generated by Django 3.0.3 on 2020-03-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0012_auto_20200314_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='jobsearcher.Scope'),
        ),
    ]
