# Generated by Django 3.0.3 on 2020-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0013_auto_20200314_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, height_field=40, null=True, upload_to='', width_field=40),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, height_field=40, null=True, upload_to='', width_field=40),
        ),
    ]
