# Generated by Django 3.0.3 on 2020-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0017_auto_20200317_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='portrait-solid.svg', null=True, upload_to='company_logos/'),
        ),
    ]
