# Generated by Django 3.0.3 on 2020-03-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0005_auto_20200320_1750'),
        ('jobsearcher', '0019_auto_20200317_1633'),
    ]

    operations = [
    ]
