# Generated by Django 3.0.3 on 2020-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0020_auto_20200322_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, default='media/applicant_logos/default.png', null=True, upload_to='applicant_logos/'),
        ),
    ]
