# Generated by Django 3.0.3 on 2020-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0021_auto_20200324_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='applicant_logos/'),
        ),
    ]
