# Generated by Django 3.0.3 on 2020-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0022_auto_20200324_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, default='applicant_logos/default.png', null=True, upload_to='applicant_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='applicant_logos/default.png', null=True, upload_to='company_logos/'),
        ),
    ]
