# Generated by Django 3.0.3 on 2020-03-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearcher', '0020_merge_20200324_1551'),
        ('jobsearcher', '0023_auto_20200325_1009'),
    ]

    operations = [
    ]
